# Generated by Django 4.2.1 on 2023-05-24 19:28

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocations',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('1322e5e0-7eb9-4dcb-b62d-9d0284f5e241'), primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
