# Generated by Django 4.2.1 on 2023-05-23 18:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocations',
            name='id',
            field=models.UUIDField(default=uuid.UUID('36cc0baf-10a7-44ec-8105-5faac148fa86'), primary_key=True, serialize=False),
        ),
    ]
