# Generated by Django 4.2.1 on 2023-05-24 19:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_geolocations_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocations',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c8e9a0b4-02c8-4ecd-8751-abc9dc252255'), primary_key=True, serialize=False),
        ),
    ]
