# Generated by Django 4.2.1 on 2023-05-24 19:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_alter_geolocations_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocations',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
