# Generated by Django 4.2.1 on 2023-05-24 19:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_alter_geolocations_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocations',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
